### ISSUE TITLE
Todo : 모달로그인

### ISSUE THREAD

**Issue by hongregii** [modulersYJ/ganoverflow-front#12]
chat에서 로그아웃 상태로 대화를 쌓아놓고, 저장하기 위해 뒤늦게 로그인 페이지로 갔다오면 chat이 다 사라짐 (왜냐. chat 내용이 state에 들어있기 때문.)

따라서 로그인을 모달창으로 띄워주면 state 유지 가능. 그렇다고 기존 로그인 페이지를 지울 필요는 없어보임!

**Comment by hongregii** [comment]
회원가입 은 redirect - 새탭열기로

**Comment by ABizCho** [comment]
#79 에 기본적으로 완성, 약간 보완 예정
