### ISSUE TITLE
랜딩페이지 디자인 관련

### ISSUE THREAD

**Issue by ABizCho** [modulersYJ/ganoverflow-front#94]
### 수평스크롤
CTA와 정보전달 둘 다 용이해보임
![image](https://github.com/modulersYJ/ganoverflow-front/assets/65459616/9ce63fb7-5114-4804-882f-846809507f04)

### 사이트내 컨텐츠 대시보드 형식으로 제시
우리에게도 꽤 괜찮은 전략
https://eopla.net/
![image](https://github.com/modulersYJ/ganoverflow-front/assets/65459616/eab32d57-7940-4a85-b1c3-e55814908418)

### 전환율 높은 심플한 예시
우리는 가치제안이 중요하다고 생각해서 그닥 적합해보이진 않음
![image](https://github.com/modulersYJ/ganoverflow-front/assets/65459616/b4f41a96-546d-49fe-891d-079859baba13)

**Comment by hongregii** [comment]
@ABizCho EO 좋아보이네요!
솔직히 GPT 랜딩페이지 (맞는지는 모르겠지만 아무튼 첫페이지) 가 쫌 별로라고 생각했어요 ㅋㅋㅋㅋ 너무 정보가 없어서
저희는 어차피 게시판 / 커뮤니티 / Q&A 가 주 기능이니까 양질의 chat게시물 위주로 랜딩하면 좋을 것 같습니다.
리서치하시느라 고생하셨어요!! 감사합니다~~~

**Comment by ABizCho** [comment]
#115
